### ISSUE TITLE
error in the middle of execution

### ISSUE THREAD

**Issue by delarosan1** [TreborNamor/TradingView-Machine-Learning-GUI#45]
Value Error: Make sure all available text input boxes are filled with a number for script to run properly
![Screenshot_2](https://user-images.githubusercontent.com/58947571/178056767-86cba28f-f808-4d3e-9e3b-119fa73d3dd2.png)
.

**Comment by TreborNamor** [comment]
In the previous version it seemed to be a problem with the script trying to add an empty string into a list. I figured out that the reason this was happened was because the program was executing faster than the webpage was loading. I was able to fix this error to give the webpage time to load. I ran 1,000 loops to make sure error was resolved in new update
